import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by the OpenNext/Workers deploy (npm run build:worker). Both
    // are gitignored, so CI never sees them — but locally ESLint would try to
    // parse ~230 MB of bundled output and die with a heap OOM.
    ".open-next/**",
    ".wrangler/**",
  ]),
]);

export default eslintConfig;
